# Generated by Django 3.0.1 on 2020-01-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
